@AuthKey = 00b88241-1c94-40ad-b796-f3c3791bce28
@BaseUrl = http://localhost:60521
# @BaseUrl = http://kikoriki.space:5000

### Login
GET {{BaseUrl}}/User?loginOrEmail=test&password=test


### Register
POST {{BaseUrl}}/User
Content-Type: application/json

{
    "FirstName":"test",
    "LastName":"test",
    "Login":"test",
    "Email":"123",
    "Password":"test"
}

### GoodProperty
GET {{BaseUrl}}/GoodProperty/{{AuthKey}}


### UserList
GET {{BaseUrl}}/UserList/{{AuthKey}}


### GoodCategory
GET {{BaseUrl}}/GoodCategory/{{AuthKey}}


### All goods
GET {{BaseUrl}}/Good/{{AuthKey}}

### DELETE GOOD
DELETE {{BaseUrl}}/Good/{{AuthKey}}/1

#### Add good
POST {{BaseUrl}}/Good HTTP/1.1
Content-Type: application/json

{
    "AuthKey" : "{{AuthKey}}",
    "Content" : {
        "Title" : "Test",
        "Text" : "Test",
        "Price" : 100,
        "GoodCategoryID" : 1
    }
}

#### UPDATE good
PATCH {{BaseUrl}}/Good HTTP/1.1
Content-Type: application/json

{
    "AuthKey" : "{{AuthKey}}",
    "Content" : {
        "ID" : 5,
        "Title" : "Test1",
        "Text" : "Test",
        "Price" : 100,
        "GoodCategoryID" : 1
    }
}


### Get properties
GET {{BaseUrl}}/GoodsProperties/{{AuthKey}}/3






#### Add to cart
POST {{BaseUrl}}/Cart
Content-Type: application/json

{
    "AuthKey" : "{{AuthKey}}",
    "Content" : {
        "Good" : {
            "ID" : 5,
            "Title" : "Test1",
            "Text" : "Test",
            "Price" : 100,
            "GoodCategoryID" : 1
        },
        "Count" : 1
    }
}
