@AuthKey = becc5c24-998a-43e8-912f-8480ddcca77a
@BaseUrl = http://localhost:60521

### Login
GET http://kikoriki.space:5000/User?email=test&password=test


### Register
POST http://kikoriki.space:5000/User
Content-Type: application/json

{
    "FirstName":"test",
    "LastName":"test",
    "Login":"test",
    "Email":"123",
    "Password":"test"
}


### Register
PATCH http://kikoriki.space:5000/User
Content-Type: application/json

{
    "FirstName":"test",
    "LastName":"test",
    "Login":"test",
    "Email":"123",
    "Password":"test"
}




### GoodProperty

GET {{BaseUrl}}/GoodProperty/{{AuthKey}}